---
image: quay.io/ansible/molecule
services:
  - docker:dind

stages:
  - tests

before_script:
  - docker -v
  - python -V
  - ansible --version
  - molecule --version

molecule:
  stage: tests
  script:
    - molecule test
