---

- name: configure_logrotate | create log directory
  file:
    path:    "{{ mysql_log_dir }}"
    state:   directory
    mode:    0750
    owner:   mysql
    group:   mysql

- name: configure_logrotate | create logrotate file
  template:
    src:   etc/logrotate.d/mysql.j2
    dest:  /etc/logrotate.d/mysql
    owner: root
    group: root
